line-length = 120
src = ["src"]

target-version = "py310"

exclude = [
    ".git",
    ".venv",
    "venv",
]

preview = false

[lint]
extend-safe-fixes = [
    "unnecessary-collection-call",    # unnecessary-collection-call
    "non-augmented-assignment", # non-augmented-assignment
    "pytest-parametrize-names-wrong-type",   # pytest-parametrize-names-wrong-type
    "unsorted-dunder-all",  # unsorted-dunder-all
    "duplicate-isinstance-call",  # duplicate-isinstance-call
    "if-else-block-instead-of-if-exp",  # if-else-block-instead-of-if-exp
    "typing-only-third-party-import",   # typing-only-third-party-import
    "non-pep585-annotation",   # non-pep585-annotation
    "non-pep604-annotation-union",   # non-pep604-annotation-union
    "deprecated-import",   # deprecated-import
    "non-pep604-isinstance",   # non-pep604-isinstance
]
extend-unsafe-fixes = [
    "blanket-type-ignore", # blanket-type-ignore
    "unused-noqa", # unused-noqa
    "invalid-rule-code", # invalid-rule-code
]
select = [
    "A",     # flake8-builtins
    "AIR",   # Airflow
    "ANN",   # flake8-annotations
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "C",     # flake8-comprehensions
    "COM",   # flake8-commas
    "D",     # pydocstyle
    "DOC",   # pydoclint
    "DTZ",   # flake8-datetimez
    "E",     # pycodestyle Error
    "ERA",   # eradicate
    "EXE",   # flake8-executable
    "F",     # Pyflakes
    "FA",    # flake8-future-annotations
    "FLY",   # flynt
    "FURB",  # refurb
    "I",     # isort
    "ICN",   # flake8-import-conventions
    "INP",   # flake8-no-pep420
    "LOG",   # flake8-logging
    "N",     # pep8-naming
    "PERF",  # Perflint
    "PGH",   # pygrep-hooks
    "PIE",   # flake8-pie
    "PL",    # Pylint
    "PT",    # flake8-pytest-style
    "PTH",   # flake8-use-pathlib
    "PYI",   # flake8-pyi
    "Q",     # flake8-quotes
    "RET",   # flake8-return
    "RSE",   # flake8-raise
    "RUF",   # Ruff-specific rules
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "T",     # flake8-debugger
    "TC",   # flake8-type-checking
    "TID",   # flake8-tidy-imports
    "TRY",   # tryceratops
    "UP",    # pyupgrade
    "W",     # pycodestyle Warning
    "YTT",   # flake8-2020
]

ignore = [
    "missing-type-kwargs",   # missing-type-kwargs
    "missing-trailing-comma",   # missing-trailing-comma
    "undocumented-public-module",     # undocumented-public-module
    "undocumented-public-class",     # undocumented-public-class
    "undocumented-public-method",     # undocumented-public-method
    "undocumented-public-function",     # undocumented-public-function
    "undocumented-public-package",     # undocumented-public-package
    "undocumented-public-init",     # undocumented-public-init
    "incorrect-blank-line-before-class",     # incorrect-blank-line-before-class
    "missing-blank-line-after-summary",     # missing-blank-line-after-summary
    "multi-line-summary-second-line",     # multi-line-summary-second-line
    "import-outside-top-level",  # import-outside-top-level
    "assert",     # assert
    "runtime-cast-value",    # runtime-cast-value
    "raise-vanilla-args",   # raise-vanilla-args
]

[lint.per-file-ignores]
"*" = []

"src/tokenfactory/rl/api_client/models.py" = [
    "commented-out-code", # commented-out-code
    "mixed-case-variable-in-class-scope",   # mixed-case-variable-in-class-scope
]

"tests/**" = [
    "D",       # pydocstyleT
    "DOC",     # pydoclint
    "implicit-namespace-package",  # implicit-namespace-package
    "PLR",     # efactor-plr
    "float-equality-comparison",  # float-equality-comparison
]

"tests/**/test_*.py" = [
    "ANN",      # flake8-annotations-ann
    "unused-unpacked-variable",   # unused-unpacked-variable
    "assert",     # assert
    "hardcoded-password-func-arg",     # hardcoded-password-func-arg
]


"!tests/**" = [
    "import-private-name", # import-private-name
]

"src/tokenfactory/rl/examples/**" = [
    "suspicious-non-cryptographic-random-usage",   # suspicious-non-cryptographic-random-usage
]

"!src/tokenfactory/rl/examples/**" = [
    "import-private-name", # import-private-name
]


[lint.mccabe]
max-complexity = 20

[lint.isort]
known-first-party = ["tokenfactory"]
known-third-party = []

combine-as-imports = false
force-sort-within-sections = false
lines-after-imports = 2
split-on-trailing-comma = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.flake8-annotations]
suppress-none-returning = true

[lint.flake8-implicit-str-concat]
allow-multiline = false

[format]
skip-magic-trailing-comma = false

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
]

[lint.pylint]
max-args = 12
