line-length = 120
src = ["contree_sdk"]

target-version = "py310"

exclude = [
    ".git",
    ".venv",
    "venv",
]

preview = true

[lint]
extend-safe-fixes = [
    "C408",    # unnecessary-collection-call
    "PT006",   # pytest-parametrize-names-wrong-type
    "RUF022",  # unsorted-dunder-all
    "SIM101",  # duplicate-isinstance-call
    "SIM108",  # if-else-block-instead-of-if-exp
    "UP006",   # non-pep585-annotation
    "UP007",   # non-pep604-annotation-union
    "UP035",   # deprecated-import
    "UP038",   # non-pep604-isinstance
    "PLR6104", # non-augmented-assignment
    "TC002",
]
extend-unsafe-fixes = [
    "PGH003", # blanket-type-ignore
    "RUF100", # unused-noqa
    "RUF102", # invalid-rule-code
]
select = [
    "A",     # flake8-builtins
    "AIR",   # Airflow
    "ANN",   # flake8-annotations
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "C",     # flake8-comprehensions
    "COM",   # flake8-commas
    "D",     # pydocstyle
    "DOC",   # pydoclint
    "E",     # pycodestyle Error
    "ERA",   # eradicate
    "EXE",   # flake8-executable
    "F",     # Pyflakes
    "FA",    # flake8-future-annotations
    "I",     # isort
    "LOG",   # flake8-logging
    "N",     # pep8-naming
    "PERF",  # Perflint
    "PGH",   # pygrep-hooks
    "PIE",   # flake8-pie
    "PL",    # Pylint
    "PT",    # flake8-pytest-style
    "PTH",   # flake8-use-pathlib
    "PYI",   # flake8-pyi
    "RET",   # flake8-return
    "RSE",   # flake8-raise
    "RUF",   # Ruff-specific rules
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "T",     # flake8-debugger
    "TCH",   # flake8-type-checking
    "TID",   # flake8-tidy-imports
    "TRY",   # tryceratops
    "UP",    # pyupgrade
    "W",     # pycodestyle Warning
    "YTT",   # flake8-2020
]

extend-ignore = [
    "ANN003", # missing-type-kwargs
    "TRY003", # raise-vanilla-args
    "D203",   # incorrect-blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "D205",
    "S101",  # assert
    "COM812",   # missing-trailing-comma
    "D100",     # undocumented-public-module
    "D101",     # undocumented-public-class
    "D102",     # undocumented-public-method
    "D103",     # undocumented-public-function
    "D104",     # undocumented-public-package
    "D107",     # undocumented-public-init
    "PLC0415",  # import-outside-top-level
    "TC006",
]

[lint.per-file-ignores]


"*" = [
]

"src/tokenfactory/rl/api_client/models.py" = [
    "ERA001",
    "N815",
]

"tests/**" = [
    "PLR",
    "D",       # pydocstyle
    "DOC",     # pydoclint
    "RUF069",
]

"tests/**/test_*.py" = [
    "ANN",      # flake8-annotations-ann
    "RUF059",   # unused-unpacked-variable
    "S101",     # assert
    "S106",     # hardcoded-password-func-arg
]


"!tests/**" = [
    "PLC2701", # import-private-name
]

"src/tokenfactory/rl/examples/**" = [
    "S311",   # suspicious-non-cryptographic-random-usage
]

"!src/tokenfactory/rl/examples/**" = [
    "PLC2701", # import-private-name
]


[lint.mccabe]
max-complexity = 20

[lint.isort]
known-first-party = ["contree_sdk"]
known-third-party = []

combine-as-imports = false
force-sort-within-sections = false
lines-after-imports = 2
split-on-trailing-comma = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.flake8-annotations]
suppress-none-returning = true

[lint.flake8-implicit-str-concat]
allow-multiline = false

[format]
skip-magic-trailing-comma = false

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
]

[lint.pylint]
max-args = 12
