# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-03-31T14:55:49+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, NonNegativeInt


class ServiceTier(Enum):
    auto = "auto"
    default = "default"
    flex = "flex"
    scale = "scale"
    priority = "priority"


class CreateBatchRequest(BaseModel):
    index: NonNegativeInt = Field(..., title="Index")


class JobStatus(BaseModel):
    object: Literal["fine_tuning.job.status"] = Field("fine_tuning.job.status", title="Object")
    inference_version: int | None = Field(..., title="Inference Version")
    total_batches: int | None = Field(..., title="Total Batches")
    filled_batches: int = Field(..., title="Filled Batches")


class Model(Enum):
    gpt_5 = "gpt-5"
    gpt_5_mini = "gpt-5-mini"
    gpt_5_nano = "gpt-5-nano"
    gpt_5_2025_08_07 = "gpt-5-2025-08-07"
    gpt_5_mini_2025_08_07 = "gpt-5-mini-2025-08-07"
    gpt_5_nano_2025_08_07 = "gpt-5-nano-2025-08-07"
    gpt_5_chat_latest = "gpt-5-chat-latest"
    gpt_4_1 = "gpt-4.1"
    gpt_4_1_mini = "gpt-4.1-mini"
    gpt_4_1_nano = "gpt-4.1-nano"
    gpt_4_1_2025_04_14 = "gpt-4.1-2025-04-14"
    gpt_4_1_mini_2025_04_14 = "gpt-4.1-mini-2025-04-14"
    gpt_4_1_nano_2025_04_14 = "gpt-4.1-nano-2025-04-14"
    o4_mini = "o4-mini"
    o4_mini_2025_04_16 = "o4-mini-2025-04-16"
    o3 = "o3"
    o3_2025_04_16 = "o3-2025-04-16"
    o3_mini = "o3-mini"
    o3_mini_2025_01_31 = "o3-mini-2025-01-31"
    o1 = "o1"
    o1_2024_12_17 = "o1-2024-12-17"
    o1_preview = "o1-preview"
    o1_preview_2024_09_12 = "o1-preview-2024-09-12"
    o1_mini = "o1-mini"
    o1_mini_2024_09_12 = "o1-mini-2024-09-12"
    gpt_4o = "gpt-4o"
    gpt_4o_2024_11_20 = "gpt-4o-2024-11-20"
    gpt_4o_2024_08_06 = "gpt-4o-2024-08-06"
    gpt_4o_2024_05_13 = "gpt-4o-2024-05-13"
    gpt_4o_audio_preview = "gpt-4o-audio-preview"
    gpt_4o_audio_preview_2024_10_01 = "gpt-4o-audio-preview-2024-10-01"
    gpt_4o_audio_preview_2024_12_17 = "gpt-4o-audio-preview-2024-12-17"
    gpt_4o_audio_preview_2025_06_03 = "gpt-4o-audio-preview-2025-06-03"
    gpt_4o_mini_audio_preview = "gpt-4o-mini-audio-preview"
    gpt_4o_mini_audio_preview_2024_12_17 = "gpt-4o-mini-audio-preview-2024-12-17"
    gpt_4o_search_preview = "gpt-4o-search-preview"
    gpt_4o_mini_search_preview = "gpt-4o-mini-search-preview"
    gpt_4o_search_preview_2025_03_11 = "gpt-4o-search-preview-2025-03-11"
    gpt_4o_mini_search_preview_2025_03_11 = "gpt-4o-mini-search-preview-2025-03-11"
    chatgpt_4o_latest = "chatgpt-4o-latest"
    codex_mini_latest = "codex-mini-latest"
    gpt_4o_mini = "gpt-4o-mini"
    gpt_4o_mini_2024_07_18 = "gpt-4o-mini-2024-07-18"
    gpt_4_turbo = "gpt-4-turbo"
    gpt_4_turbo_2024_04_09 = "gpt-4-turbo-2024-04-09"
    gpt_4_0125_preview = "gpt-4-0125-preview"
    gpt_4_turbo_preview = "gpt-4-turbo-preview"
    gpt_4_1106_preview = "gpt-4-1106-preview"
    gpt_4_vision_preview = "gpt-4-vision-preview"
    gpt_4 = "gpt-4"
    gpt_4_0314 = "gpt-4-0314"
    gpt_4_0613 = "gpt-4-0613"
    gpt_4_32k = "gpt-4-32k"
    gpt_4_32k_0314 = "gpt-4-32k-0314"
    gpt_4_32k_0613 = "gpt-4-32k-0613"
    gpt_3_5_turbo = "gpt-3.5-turbo"
    gpt_3_5_turbo_16k = "gpt-3.5-turbo-16k"
    gpt_3_5_turbo_0301 = "gpt-3.5-turbo-0301"
    gpt_3_5_turbo_0613 = "gpt-3.5-turbo-0613"
    gpt_3_5_turbo_1106 = "gpt-3.5-turbo-1106"
    gpt_3_5_turbo_0125 = "gpt-3.5-turbo-0125"
    gpt_3_5_turbo_16k_0613 = "gpt-3.5-turbo-16k-0613"


class FunctionCall(Enum):
    none = "none"
    auto = "auto"


class Modality(Enum):
    text = "text"
    audio = "audio"


class ReasoningEffort(Enum):
    minimal = "minimal"
    low = "low"
    medium = "medium"
    high = "high"


class ToolChoice(Enum):
    none = "none"
    auto = "auto"
    required = "required"


class Verbosity(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class Stream(Enum):
    boolean_False = False
    boolean_None = None


class Model1(Enum):
    gpt_3_5_turbo_instruct = "gpt-3.5-turbo-instruct"
    davinci_002 = "davinci-002"
    babbage_002 = "babbage-002"


class BatchStatus(Enum):
    filling = "filling"
    filled = "filled"


class Format(Enum):
    wav = "wav"
    aac = "aac"
    mp3 = "mp3"
    flac = "flac"
    opus = "opus"
    pcm16 = "pcm16"


class Voice(Enum):
    alloy = "alloy"
    ash = "ash"
    ballad = "ballad"
    coral = "coral"
    echo = "echo"
    sage = "sage"
    shimmer = "shimmer"
    verse = "verse"


class ChatCompletionAudioParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    format: Format = Field(..., title="Format")
    voice: str | Voice = Field(..., title="Voice")


class ChatCompletionFunctionCallOptionParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")


class ChatCompletionFunctionMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | None = Field(..., title="Content")
    name: str = Field(..., title="Name")
    role: Literal["function"] = Field(..., title="Role")


class ChatCompletionStreamOptionsParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    include_obfuscation: bool | None = Field(None, title="Include Obfuscation")
    include_usage: bool | None = Field(None, title="Include Usage")


class FinishReason(Enum):
    stop = "stop"
    length = "length"
    tool_calls = "tool_calls"
    content_filter = "content_filter"
    function_call = "function_call"


class FinishReason1(Enum):
    stop = "stop"
    length = "length"
    content_filter = "content_filter"


class ResponseFormatJSONObject(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["json_object"] = Field(..., title="Type")


class ResponseFormatText(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["text"] = Field(..., title="Type")


class Sample(BaseModel):
    object: Literal["fine_tuning.rl_sample"] = Field("fine_tuning.rl_sample", title="Object")
    id: str = Field(..., title="Id")
    token_ids: list[int] = Field(..., title="Token Ids")
    logprobs: list[float] = Field(..., title="Logprobs")
    mask: list[int] = Field(..., title="Mask")
    normalized_reward: float = Field(..., title="Normalized Reward")
    metadata: dict[str, str] = Field(..., title="Metadata")
    debug_info: dict[str, Any] = Field(..., title="Debug Info")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class SearchContextSize(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class OpenaiTypesChatCompletionCreateParamsFunction(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    parameters: dict[str, Any] | None = Field(None, title="Parameters")


class Audio(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")


class Mode(Enum):
    auto = "auto"
    required = "required"


class ChatCompletionAllowedToolsParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Mode = Field(..., title="Mode")
    tools: list[dict[str, Any]] = Field(..., title="Tools")


class ChatCompletionContentPartRefusalParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    refusal: str = Field(..., title="Refusal")
    type: Literal["refusal"] = Field(..., title="Type")


class ChatCompletionContentPartTextParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    text: str = Field(..., title="Text")
    type: Literal["text"] = Field(..., title="Type")


class CompletionTokensDetails(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    accepted_prediction_tokens: int | None = Field(None, title="Accepted Prediction Tokens")
    audio_tokens: int | None = Field(None, title="Audio Tokens")
    reasoning_tokens: int | None = Field(None, title="Reasoning Tokens")
    rejected_prediction_tokens: int | None = Field(None, title="Rejected Prediction Tokens")


class FunctionCallModel(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    arguments: str = Field(..., title="Arguments")
    name: str = Field(..., title="Name")


class FunctionDefinition(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    parameters: dict[str, Any] | None = Field(None, title="Parameters")
    strict: bool | None = Field(None, title="Strict")


class JSONSchema(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    schema_: dict[str, Any] | None = Field(None, alias="schema", title="Schema")
    strict: bool | None = Field(None, title="Strict")


class Logprobs(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    text_offset: list[int] | None = Field(None, title="Text Offset")
    token_logprobs: list[float] | None = Field(None, title="Token Logprobs")
    tokens: list[str] | None = Field(None, title="Tokens")
    top_logprobs: list[dict[str, float]] | None = Field(None, title="Top Logprobs")


class PromptTokensDetails(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    audio_tokens: int | None = Field(None, title="Audio Tokens")
    cached_tokens: int | None = Field(None, title="Cached Tokens")


class OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")


class OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., title="Name")


class ChatCompletionAudio(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    data: str = Field(..., title="Data")
    expires_at: int = Field(..., title="Expires At")
    transcript: str = Field(..., title="Transcript")


class FileFile(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    file_data: str | None = Field(None, title="File Data")
    file_id: str | None = Field(None, title="File Id")
    filename: str | None = Field(None, title="Filename")


class Detail(Enum):
    auto = "auto"
    low = "low"
    high = "high"


class ImageURL(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: str = Field(..., title="Url")
    detail: Detail | None = Field(None, title="Detail")


class Format1(Enum):
    wav = "wav"
    mp3 = "mp3"


class InputAudio(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    data: str = Field(..., title="Data")
    format: Format1 = Field(..., title="Format")


class WebSearchOptionsUserLocationApproximate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    city: str | None = Field(None, title="City")
    country: str | None = Field(None, title="Country")
    region: str | None = Field(None, title="Region")
    timezone: str | None = Field(None, title="Timezone")


class OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input: str = Field(..., title="Input")
    name: str = Field(..., title="Name")


class OpenaiTypesChatChatCompletionMessageFunctionToolCallParamFunction(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    arguments: str = Field(..., title="Arguments")
    name: str = Field(..., title="Name")


class AnnotationURLCitation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    end_index: int = Field(..., title="End Index")
    start_index: int = Field(..., title="Start Index")
    title: str = Field(..., title="Title")
    url: str = Field(..., title="Url")


class CustomOutput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input: str = Field(..., title="Input")
    name: str = Field(..., title="Name")


class FunctionOutput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    arguments: str = Field(..., title="Arguments")
    name: str = Field(..., title="Name")


class TopLogprob(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    token: str = Field(..., title="Token")
    bytes: list[int] | None = Field(None, title="Bytes")
    logprob: float = Field(..., title="Logprob")


class Batch(BaseModel):
    object: Literal["fine_tuning.batch"] = Field("fine_tuning.batch", title="Object")
    index: NonNegativeInt = Field(..., title="Index")
    status: BatchStatus | None = BatchStatus.filling
    sample_count: NonNegativeInt | None = Field(0, title="Sample Count")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class OpenAICompletionRequest(BaseModel):
    model: str | Model1 = Field(..., title="Model")
    prompt: str | list[int] | list[str] = Field(..., title="Prompt")
    best_of: int | None = Field(None, title="Best Of")
    echo: bool | None = Field(None, title="Echo")
    frequency_penalty: float | None = Field(None, title="Frequency Penalty")
    logit_bias: dict[str, int] | None = Field(None, title="Logit Bias")
    logprobs: int | None = Field(None, title="Logprobs")
    max_tokens: int | None = Field(None, title="Max Tokens")
    n: int | None = Field(None, title="N")
    presence_penalty: float | None = Field(None, title="Presence Penalty")
    seed: int | None = Field(None, title="Seed")
    stop: str | list[str] | None = Field(None, title="Stop")
    stream_options: ChatCompletionStreamOptionsParam | None = None
    suffix: str | None = Field(None, title="Suffix")
    temperature: float | None = Field(None, title="Temperature")
    top_p: float | None = Field(None, title="Top P")
    user: str | None = Field(None, title="User")
    stream: Stream | None = Field(None, title="Stream")
    extra_body: dict[str, Any] | None = Field(None, title="Extra Body")


class UploadSamplesRequest(BaseModel):
    samples: list[Sample] = Field(..., title="Samples")


class ChatCompletionAllowedToolChoiceParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    allowed_tools: ChatCompletionAllowedToolsParam
    type: Literal["allowed_tools"] = Field(..., title="Type")


class ChatCompletionDeveloperMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | list[ChatCompletionContentPartTextParam] = Field(..., title="Content")
    role: Literal["developer"] = Field(..., title="Role")
    name: str | None = Field(None, title="Name")


class ChatCompletionFunctionToolParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    function: FunctionDefinition
    type: Literal["function"] = Field(..., title="Type")


class ChatCompletionNamedToolChoiceCustomParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    custom: OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom
    type: Literal["custom"] = Field(..., title="Type")


class ChatCompletionNamedToolChoiceParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    function: OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction
    type: Literal["function"] = Field(..., title="Type")


class ChatCompletionPredictionContentParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | list[ChatCompletionContentPartTextParam] = Field(..., title="Content")
    type: Literal["content"] = Field(..., title="Type")


class ChatCompletionSystemMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | list[ChatCompletionContentPartTextParam] = Field(..., title="Content")
    role: Literal["system"] = Field(..., title="Role")
    name: str | None = Field(None, title="Name")


class ChatCompletionToolMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | list[ChatCompletionContentPartTextParam] = Field(..., title="Content")
    role: Literal["tool"] = Field(..., title="Role")
    tool_call_id: str = Field(..., title="Tool Call Id")


class CompletionChoice(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    finish_reason: FinishReason1 = Field(..., title="Finish Reason")
    index: int = Field(..., title="Index")
    logprobs: Logprobs | None = None
    text: str = Field(..., title="Text")


class CompletionUsage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    completion_tokens: int = Field(..., title="Completion Tokens")
    prompt_tokens: int = Field(..., title="Prompt Tokens")
    total_tokens: int = Field(..., title="Total Tokens")
    completion_tokens_details: CompletionTokensDetails | None = None
    prompt_tokens_details: PromptTokensDetails | None = None


class ResponseFormatJSONSchema(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    json_schema: JSONSchema
    type: Literal["json_schema"] = Field(..., title="Type")


class ChatCompletionContentPartImageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    image_url: ImageURL
    type: Literal["image_url"] = Field(..., title="Type")


class ChatCompletionContentPartInputAudioParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_audio: InputAudio
    type: Literal["input_audio"] = Field(..., title="Type")


class ChatCompletionMessageCustomToolCallParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    custom: OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom
    type: Literal["custom"] = Field(..., title="Type")


class ChatCompletionMessageFunctionToolCallParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    function: OpenaiTypesChatChatCompletionMessageFunctionToolCallParamFunction
    type: Literal["function"] = Field(..., title="Type")


class File(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    file: FileFile
    type: Literal["file"] = Field(..., title="Type")


class WebSearchOptionsUserLocation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    approximate: WebSearchOptionsUserLocationApproximate
    type: Literal["approximate"] = Field(..., title="Type")


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["url_citation"] = Field(..., title="Type")
    url_citation: AnnotationURLCitation


class ChatCompletionMessageCustomToolCall(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    custom: CustomOutput
    type: Literal["custom"] = Field(..., title="Type")


class ChatCompletionMessageFunctionToolCall(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    function: FunctionOutput
    type: Literal["function"] = Field(..., title="Type")


class ChatCompletionTokenLogprob(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    token: str = Field(..., title="Token")
    bytes: list[int] | None = Field(None, title="Bytes")
    logprob: float = Field(..., title="Logprob")
    top_logprobs: list[TopLogprob] = Field(..., title="Top Logprobs")


class Completion(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    choices: list[CompletionChoice] = Field(..., title="Choices")
    created: int = Field(..., title="Created")
    model: str = Field(..., title="Model")
    object: Literal["text_completion"] = Field(..., title="Object")
    system_fingerprint: str | None = Field(None, title="System Fingerprint")
    usage: CompletionUsage | None = None


class ChatCompletionAssistantMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["assistant"] = Field(..., title="Role")
    audio: Audio | None = None
    content: str | list[ChatCompletionContentPartTextParam | ChatCompletionContentPartRefusalParam] | None = Field(
        None, title="Content"
    )
    function_call: FunctionCallModel | None = None
    name: str | None = Field(None, title="Name")
    refusal: str | None = Field(None, title="Refusal")
    tool_calls: list[ChatCompletionMessageFunctionToolCallParam | ChatCompletionMessageCustomToolCallParam] | None = (
        Field(None, title="Tool Calls")
    )


class ChatCompletionUserMessageParam(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: (
        str
        | list[
            ChatCompletionContentPartTextParam
            | ChatCompletionContentPartImageParam
            | ChatCompletionContentPartInputAudioParam
            | File
        ]
    ) = Field(..., title="Content")
    role: Literal["user"] = Field(..., title="Role")
    name: str | None = Field(None, title="Name")


class WebSearchOptions(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    search_context_size: SearchContextSize | None = Field(None, title="Search Context Size")
    user_location: WebSearchOptionsUserLocation | None = None


class ChatCompletionMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: str | None = Field(None, title="Content")
    refusal: str | None = Field(None, title="Refusal")
    role: Literal["assistant"] = Field(..., title="Role")
    annotations: list[Annotation] | None = Field(None, title="Annotations")
    audio: ChatCompletionAudio | None = None
    function_call: FunctionCallModel | None = None
    tool_calls: list[ChatCompletionMessageFunctionToolCall | ChatCompletionMessageCustomToolCall] | None = Field(
        None, title="Tool Calls"
    )


class ChoiceLogprobs(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: list[ChatCompletionTokenLogprob] | None = Field(None, title="Content")
    refusal: list[ChatCompletionTokenLogprob] | None = Field(None, title="Refusal")


class OpenAIChatCompletionRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    messages: list[
        ChatCompletionDeveloperMessageParam
        | ChatCompletionSystemMessageParam
        | ChatCompletionUserMessageParam
        | ChatCompletionAssistantMessageParam
        | ChatCompletionToolMessageParam
        | ChatCompletionFunctionMessageParam
    ] = Field(..., title="Messages")
    model: str | Model = Field(..., title="Model")
    audio: ChatCompletionAudioParam | None = None
    frequency_penalty: float | None = Field(None, title="Frequency Penalty")
    function_call: FunctionCall | ChatCompletionFunctionCallOptionParam | None = Field(None, title="Function Call")
    functions: list[OpenaiTypesChatCompletionCreateParamsFunction] | None = Field(None, title="Functions")
    logit_bias: dict[str, int] | None = Field(None, title="Logit Bias")
    logprobs: bool | None = Field(None, title="Logprobs")
    max_completion_tokens: int | None = Field(None, title="Max Completion Tokens")
    max_tokens: int | None = Field(None, title="Max Tokens")
    metadata: dict[str, str] | None = Field(None, title="Metadata")
    modalities: list[Modality] | None = Field(None, title="Modalities")
    n: int | None = Field(None, title="N")
    parallel_tool_calls: bool | None = Field(None, title="Parallel Tool Calls")
    prediction: ChatCompletionPredictionContentParam | None = None
    presence_penalty: float | None = Field(None, title="Presence Penalty")
    prompt_cache_key: str | None = Field(None, title="Prompt Cache Key")
    reasoning_effort: ReasoningEffort | None = Field(None, title="Reasoning Effort")
    response_format: ResponseFormatText | ResponseFormatJSONSchema | ResponseFormatJSONObject | None = Field(
        None, title="Response Format"
    )
    safety_identifier: str | None = Field(None, title="Safety Identifier")
    seed: int | None = Field(None, title="Seed")
    service_tier: ServiceTier | None = Field(None, title="Service Tier")
    stop: str | list[str] | None = Field(None, title="Stop")
    store: bool | None = Field(None, title="Store")
    stream_options: ChatCompletionStreamOptionsParam | None = None
    temperature: float | None = Field(None, title="Temperature")
    tool_choice: (
        ToolChoice
        | ChatCompletionAllowedToolChoiceParam
        | ChatCompletionNamedToolChoiceParam
        | ChatCompletionNamedToolChoiceCustomParam
        | None
    ) = Field(None, title="Tool Choice")
    tools: list[ChatCompletionFunctionToolParam] | None = Field(None, title="Tools")
    top_logprobs: int | None = Field(None, title="Top Logprobs")
    top_p: float | None = Field(None, title="Top P")
    user: str | None = Field(None, title="User")
    verbosity: Verbosity | None = Field(None, title="Verbosity")
    web_search_options: WebSearchOptions | None = None
    stream: Stream | None = Field(None, title="Stream")


class Choice(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    finish_reason: FinishReason = Field(..., title="Finish Reason")
    index: int = Field(..., title="Index")
    logprobs: ChoiceLogprobs | None = None
    message: ChatCompletionMessage


class ChatCompletion(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    choices: list[Choice] = Field(..., title="Choices")
    created: int = Field(..., title="Created")
    model: str = Field(..., title="Model")
    object: Literal["chat.completion"] = Field(..., title="Object")
    service_tier: ServiceTier | None = Field(None, title="Service Tier")
    system_fingerprint: str | None = Field(None, title="System Fingerprint")
    usage: CompletionUsage | None = None
