# generated by datamodel-codegen:
#   filename:  openapi-fine-tuning.yaml
#   timestamp: 2026-07-04T15:23:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, NonNegativeFloat, PositiveFloat, RootModel, SecretStr


class Suffix(RootModel[str]):
    root: str = Field(..., max_length=64, title="Suffix")


class Status(Enum):
    validating_files = "validating_files"
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class Suffix1(RootModel[str]):
    root: str = Field(
        ..., description="The suffix that will be used for output model name", max_length=64, title="Suffix"
    )


class Error(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str = Field(..., title="Code")
    message: str = Field(..., title="Message")
    param: str | None = Field(None, title="Param")


class FTCheckpointParameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["ft"] | None = Field("ft", title="Type")


class Level(Enum):
    info = "info"
    warn = "warn"
    error = "error"


class Type(Enum):
    message = "message"
    metrics = "metrics"


class FineTuningJobEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    created_at: int = Field(..., title="Created At")
    level: Level = Field(..., title="Level")
    message: str = Field(..., title="Message")
    object: Literal["fine_tuning.job.event"] = Field(..., title="Object")
    data: Any = Field(None, title="Data")
    type: Type | None = Field(None, title="Type")


class HFCheckpointParametersRequestInput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["hf"] | None = Field("hf", title="Type")
    repo: str = Field(..., title="Repo")
    revision: str | None = Field(None, title="Revision")
    token: SecretStr | None = Field(None, title="Token")


class HFCheckpointParametersResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["hf"] | None = Field("hf", title="Type")
    repo: str = Field(..., title="Repo")
    revision: str | None = Field(None, title="Revision")


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    full_valid_loss: float | None = Field(None, title="Full Valid Loss")
    full_valid_mean_token_accuracy: float | None = Field(None, title="Full Valid Mean Token Accuracy")
    step: float | None = Field(None, title="Step")
    train_loss: float | None = Field(None, title="Train Loss")
    train_mean_token_accuracy: float | None = Field(None, title="Train Mean Token Accuracy")
    valid_loss: float | None = Field(None, title="Valid Loss")
    valid_mean_token_accuracy: float | None = Field(None, title="Valid Mean Token Accuracy")


class SupervisedHParameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    batch_size: int | None = Field(8, description="Batch size for training", ge=1, le=64, title="Batch Size")
    learning_rate: NonNegativeFloat | None = Field(
        1e-05, description="Learning rate for training", title="Learning Rate"
    )
    n_epochs: int | None = Field(3, description="Number of epochs for training", ge=1, le=20, title="N Epochs")
    warmup_ratio: NonNegativeFloat | None = Field(
        0.0, description="Warmup ratio for learning rate", le=1, title="Warmup Ratio"
    )
    weight_decay: NonNegativeFloat | None = Field(0.0, description="Weight decay for optimizer", title="Weight Decay")
    packing: bool | None = Field(True, description="Whether to use packing for training", title="Packing")
    max_grad_norm: PositiveFloat | None = Field(
        1.0, description="Maximum gradient norm for optimizer", title="Max Grad Norm"
    )
    context_length: int | None = Field(
        8192, description="Context length for training", ge=8192, le=131072, title="Context Length"
    )
    lora: bool | None = Field(False, description="Whether to use LoRA (Low-Rank Adaptation) for training", title="Lora")
    lora_r: int | None = Field(8, description="Rank for LoRA", ge=8, le=128, title="Lora R")
    lora_alpha: int | None = Field(8, description="Alpha parameter for LoRA", ge=8, title="Lora Alpha")
    lora_dropout: NonNegativeFloat | None = Field(0.0, description="Dropout rate for LoRA", le=1, title="Lora Dropout")


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class AppModelsFineTuningFineTuningJobCheckpoint(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    created_at: int = Field(..., title="Created At")
    fine_tuned_model_checkpoint: str = Field(..., title="Fine Tuned Model Checkpoint")
    fine_tuning_job_id: str = Field(..., title="Fine Tuning Job Id")
    metrics: Metrics
    object: Literal["fine_tuning.job.checkpoint"] = Field(..., title="Object")
    step_number: int = Field(..., title="Step Number")
    result_files: list[str] = Field(..., title="Result Files")


class HfExportConfigRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    output_repo_name: str = Field(..., title="Output Repo Name")
    api_token: SecretStr = Field(..., title="Api Token")


class HfExportConfigResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    output_repo_name: str = Field(..., title="Output Repo Name")


class MlflowConfigRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tracking_uri: str = Field(..., title="Tracking Uri")
    experiment_name: str | None = Field(..., title="Experiment Name")
    run_name: str | None = Field(..., title="Run Name")
    tags: dict[str, str] | None = Field(None, title="Tags")
    certificate_file: str = Field(..., title="Certificate File")
    certificate_file_id: str | None = Field(None, title="Certificate File Id")
    username: str = Field(..., title="Username")
    password: SecretStr = Field(..., title="Password")


class MlflowConfigResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tracking_uri: str = Field(..., title="Tracking Uri")
    experiment_name: str | None = Field(..., title="Experiment Name")
    run_name: str | None = Field(..., title="Run Name")
    tags: dict[str, str] | None = Field(None, title="Tags")


class SupervisedConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    hyperparameters: SupervisedHParameters


class WandbConfigRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    project: str = Field(..., title="Project")
    name: str | None = Field(None, title="Name")
    entity: str | None = Field(None, title="Entity")
    tags: list[str] | None = Field(None, title="Tags")
    api_key: SecretStr = Field(..., title="Api Key")


class WandbConfigResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    project: str = Field(..., title="Project")
    name: str | None = Field(None, title="Name")
    entity: str | None = Field(None, title="Entity")
    tags: list[str] | None = Field(None, title="Tags")


class Type1(Enum):
    kl = "kl"
    lk_alpha = "lk_alpha"
    lk_hybrid = "lk_hybrid"


class SpecDraftLossParams(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Type1 | None = Field(Type1.kl, title="Type")


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    detail: list[ValidationError] | None = Field(None, title="Detail")


class ListCheckpointsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: str | None = Field("list", title="Object")
    data: list[AppModelsFineTuningFineTuningJobCheckpoint] = Field(..., title="Data")
    first_id: str | None = Field(None, title="First Id")
    last_id: str | None = Field(None, title="Last Id")
    has_more: bool | None = Field(False, title="Has More")


class ListEventsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: str | None = Field("list", description="The object type, which is always 'list'", title="Object")
    data: list[FineTuningJobEvent] = Field(..., title="Data")
    has_more: bool | None = Field(False, title="Has More")


class OpenaiTypesFineTuningJobsFineTuningJobCheckpointFineTuningJobCheckpoint(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    created_at: int = Field(..., title="Created At")
    fine_tuned_model_checkpoint: str = Field(..., title="Fine Tuned Model Checkpoint")
    fine_tuning_job_id: str = Field(..., title="Fine Tuning Job Id")
    metrics: Metrics
    object: Literal["fine_tuning.job.checkpoint"] = Field(..., title="Object")
    step_number: int = Field(..., title="Step Number")


class HfExportIntegrationRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["hf"] | None = Field("hf", title="Type")
    hf: HfExportConfigRequest


class HfExportIntegrationResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["hf"] | None = Field("hf", title="Type")
    hf: HfExportConfigResponse


class MlflowIntegrationRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["mlflow"] = Field("mlflow", title="Type")
    mlflow: MlflowConfigRequest


class MlflowIntegrationResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["mlflow"] = Field("mlflow", title="Type")
    mlflow: MlflowConfigResponse


class SupervisedMethodConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["supervised"] = Field("supervised", title="Type")
    supervised: SupervisedConfig


class WandbIntegrationRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["wandb"] | None = Field("wandb", title="Type")
    wandb: WandbConfigRequest


class WandbIntegrationResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | Literal["wandb"] | None = Field("wandb", title="Type")
    wandb: WandbConfigResponse


class SpecDraftHParameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    batch_size: int | None = Field(8, description="Batch size for training", ge=1, le=64, title="Batch Size")
    learning_rate: PositiveFloat | None = Field(
        0.0075, description="Learning rate for training", lt=1, title="Learning Rate"
    )
    n_epochs: int | None = Field(1, description="Number of epochs for training", ge=1, le=20, title="N Epochs")
    warmup_ratio: NonNegativeFloat | None = Field(
        0.0, description="Warmup ratio for learning rate", le=1, title="Warmup Ratio"
    )
    weight_decay: NonNegativeFloat | None = Field(0.0, description="Weight decay for optimizer", title="Weight Decay")
    packing: bool | None = Field(True, description="Whether to use packing for training", title="Packing")
    max_grad_norm: PositiveFloat | None = Field(
        1.0, description="Maximum gradient norm for optimizer", title="Max Grad Norm"
    )
    context_length: int | None = Field(
        8192, description="Context length for training", ge=8192, le=131072, title="Context Length"
    )
    architecture: str | None = Field("eagle3_original", title="Architecture")
    num_decoding_heads: int | None = Field(
        3, description="Number of speculative decoding heads", ge=1, le=10, title="Num Decoding Heads"
    )
    loss: SpecDraftLossParams | None = Field(None, description="Speculative drafter loss configuration")


class SpecDraftConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    hyperparameters: SpecDraftHParameters


class SpecDraftMethodConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["spec-draft"] = Field("spec-draft", title="Type")
    spec_draft: SpecDraftConfig


class FineTuningJob(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., title="Id")
    created_at: int = Field(..., title="Created At")
    error: Error | None = None
    finished_at: int | None = Field(None, title="Finished At")
    hyperparameters: SupervisedHParameters | None = None
    method: SupervisedMethodConfig | SpecDraftMethodConfig | None = Field(None, title="Method")
    integrations: list[WandbIntegrationResponse | MlflowIntegrationResponse | HfExportIntegrationResponse] | None = (
        Field(None, title="Integrations")
    )
    from_checkpoint: HFCheckpointParametersResponse | FTCheckpointParameters | None = Field(
        None, title="From Checkpoint"
    )
    model: str = Field(..., title="Model")
    object: Literal["fine_tuning.job"] = Field("fine_tuning.job", title="Object")
    organization_id: str | None = Field("", title="Organization Id")
    result_files: list[str] | None = Field([], title="Result Files")
    seed: int | None = Field(0, title="Seed")
    suffix: Suffix | None = Field(None, title="Suffix")
    status: Status = Field(..., title="Status")
    trained_tokens: int | None = Field(None, title="Trained Tokens")
    training_file: str = Field(..., title="Training File")
    validation_file: str | None = Field(None, title="Validation File")
    estimated_finish: int | None = Field(None, title="Estimated Finish")
    trained_steps: int | None = Field(None, title="Trained Steps")
    total_steps: int | None = Field(None, title="Total Steps")


class FineTuningJobListResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: str | None = Field("list", description="The object type, which is always 'list'", title="Object")
    data: list[FineTuningJob] = Field(..., description="List of fine-tuning jobs", title="Data")
    has_more: bool = Field(..., description="Whether there are more jobs to fetch", title="Has More")


class FineTuningRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model: str = Field(
        ...,
        description="The name of the model to fine-tune",
        examples=[
            "meta-llama/Llama-3.1-70B-Instruct",
            "meta-llama/Llama-3.1-70B",
            "meta-llama/Llama-3.1-8B-Instruct",
            "meta-llama/Llama-3.1-8B",
        ],
        title="Model",
    )
    from_checkpoint: HFCheckpointParametersRequestInput | FTCheckpointParameters | None = Field(
        None, description="Checkpoint to continue training from", title="From Checkpoint"
    )
    training_file: str = Field(
        ..., description="The ID of the uploaded training data file", examples=["file_123456"], title="Training File"
    )
    validation_file: str | None = Field(
        None,
        description="The ID of the uploaded validation data file",
        examples=["file_123456"],
        title="Validation File",
    )
    hyperparameters: SupervisedHParameters | None = Field(None, description="Training hyperparameters")
    method: SupervisedMethodConfig | SpecDraftMethodConfig | None = Field(
        None, description="Fine-tuning method configuration", title="Method"
    )
    integrations: list[WandbIntegrationRequest | MlflowIntegrationRequest | HfExportIntegrationRequest] | None = Field(
        None, description="Job integration paramaters", title="Integrations"
    )
    seed: int | None = Field(
        None, description="The seed controls the reproducibility of the job", examples=[42], title="Seed"
    )
    suffix: Suffix1 | None = Field(
        None, description="The suffix that will be used for output model name", title="Suffix"
    )
    tags: list[str] | None = Field(
        None, description="List of tags to associate with the job", examples=["my-ft-job"], title="Tags"
    )
    extra_body: dict[str, Any] | None = Field(
        None, description="Extra params to pass to the fine-tuning job", title="Extra Body"
    )
