# generated by datamodel-codegen:
#   filename:  openapi-rl-job.yaml
#   timestamp: 2026-07-04T15:23:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, NonNegativeInt


class CreateBatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    index: NonNegativeInt = Field(..., title="Index")


class JobStatus(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: Literal["fine_tuning.job.status"] = Field("fine_tuning.job.status", title="Object")
    inference_version: int | None = Field(..., title="Inference Version")
    total_batches: int | None = Field(..., title="Total Batches")
    filled_batches: int = Field(..., title="Filled Batches")


class BatchStatus(Enum):
    filling = "filling"
    filled = "filled"


class Sample(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: Literal["fine_tuning.rl_sample"] = Field("fine_tuning.rl_sample", title="Object")
    id: str = Field(..., title="Id")
    token_ids: list[int] = Field(..., title="Token Ids")
    logprobs: list[float] = Field(..., title="Logprobs")
    mask: list[int] = Field(..., title="Mask")
    normalized_reward: float = Field(..., title="Normalized Reward")
    metadata: dict[str, str] = Field(..., title="Metadata")
    debug_info: dict[str, Any] = Field(..., title="Debug Info")


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class Batch(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: Literal["fine_tuning.batch"] = Field("fine_tuning.batch", title="Object")
    index: NonNegativeInt = Field(..., title="Index")
    status: BatchStatus | None = BatchStatus.filling
    sample_count: NonNegativeInt | None = Field(0, title="Sample Count")


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    detail: list[ValidationError] | None = Field(None, title="Detail")


class UploadSamplesRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    samples: list[Sample] = Field(..., title="Samples")
